# This is used to integrate with the Travis CI server at travis-ci.org
language: android
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a

android:
  components:
    # android-19 is used to run the tests on
    - platform-tools
    - tools
    - build-tools-24.0.2
    - $ANDROID_TARGET
    - android-19
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
    - sys-img-${ANDROID_ABI}-android-19
    - extra-android-m2repository

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-19 --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &